import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Header } from './components'
import Image from 'next/image'
import {pokeBall, el121, el122, el123, el125, el126, el127, el128, el120, el130} from '@/assets/images/bg_elements'
import { StaticImport } from 'next/dist/shared/lib/get-img-props'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const BG_ELEMENTS = [
  {
    src: pokeBall,
    width: 420,
    height: 420,
    style: {
      top: "0px",
      right: "-12em",
      rotate: "-23.49deg"
    }
  },
  {
    src: pokeBall,
    width: 179.11,
    height: 179.11,
    style: {
      bottom: "14em",
      left: "-3em",
      rotate: "19.9deg"
    }
  },
  {
    src: el122,
    width: 65.2,
    height: 89.02,
    style: {
      bottom: "12em",
      left: "4em",
    }
  },
  {
    src: el123,
    width: 65.2,
    height: 89.02,
    style: {
      bottom: "27em",
      left: "0.5em",
      rotate: "8.37deg"
    }
  },
  {
    src: el120,
    width: 40.02,
    height: 51,
    style: {
      bottom: "35em",
      left: "9em",
      rotate: "20.05deg"
    }
  },
  {
    src: el130,
    width: 33.02,
    height: 37.89,
    style: {
      bottom: "23em",
      left: "11em",
      rotate: "20.05deg"
    }
  },
  {
    src: el126,
    width: 33.02,
    height: 37.89,
    style: {
      width: 36.78,
      height: 43.60,
      bottom: "12em",
      left: "16em",
      rotate: "-25.7deg"
    }
  },
]

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`bg-gray-900 ${inter.className}`}>
        <Header/>
        <div className="relative">
          {
            BG_ELEMENTS.map(({style, ...rest}, idx) => (
              <Image {...rest} style={{position: "absolute", ...style}} alt={`bg_el_${idx}`} loading='lazy'/>
            ))
          }
          
          {children}
        </div>
      </body>
    </html>
  )
}
