import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Header } from './components'
import Image from 'next/image'
import {pokeBall, el121, el122, el123, el125, el126, el127, el128, el120, el130} from '@/assets/images/bg_elements'
import { StaticImport } from 'next/dist/shared/lib/get-img-props'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const BG_ELEMENTS = [
  {
    src: pokeBall,
    width: 420,
    height: 420,
    style: {
      top: "216.44",
      left: "1104px",
      rotate: "-23.49 deg"
    }
  }
]

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`bg-gray-900 ${inter.className}`}>
        <Header/>
        <div className="relative">
          {
            BG_ELEMENTS.map(({style, ...rest}, idx) => (
              <Image {...rest} style={{position: "absolute", ...style}} alt={`bg_el_${idx}`} loading='lazy'/>
            ))
          }
          
          {children}
        </div>
      </body>
    </html>
  )
}
